services:
  - type: web
    name: bytexl-image-converter
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    healthCheckPath: /healthz
    envVars:
      - key: BYTEXL_UPLOAD_TOKEN
        sync: false
      - key: BYTEXL_UPLOAD_URL
        value: https://bytexl.app/api/upload/s3
